### ISSUE TITLE
TiffStyle decoder panics on some malformed input

### ISSUE THREAD

**Issue by 197g** [redwarp/lzw#1]
Input as base64: `H0A6AAAARAAARABgVA==`

With [cargo fuzz](https://rust-fuzz.github.io/book/cargo-fuzz.html) setup:

```rust
#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let ref mut output = vec![];
    let _ = salzweg::decoder::TiffStyleDecoder::decode(data, output);
});
```

```text
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /salzweg/lzw/src/decoder.rs:257:25
```

**Comment by redwarp** [comment]
Oh, I'll take a look tomorrow!

**Comment by redwarp** [comment]
Good find, I added a check to prevent the decoding stack from, well, dying when the word we decode is simply wrong. Returns an error instead of panickin.
