### ISSUE TITLE
An lzw-like compress/decompress

### ISSUE THREAD

**Issue by v1gnesh** [redwarp/lzw#3]
Hi,

Firstly, thank you for sharing your excellent work!

There's an compression format called terse, and IBM has published a decompresser for it -
https://github.com/openmainframeproject/tersedecompress

If/when you have time, would you be able to look at this to add support for it to this crate.
Or maybe advise on what I'd need to change.
It also works with 12 bits of input at a time.
There are 2 variants - PACK and SPACK. I'm only interested in the PACK variant.

I can share a Rust "port" of the above Java impl privately, if that'll help.

Thanks in advance for any guidance you can give.
PS: I'm pretty novice w.r.t programming; so it'd take ages for me to fully understand your work.

**Comment by v1gnesh** [comment]
Any thoughts, @redwarp ?

**Comment by redwarp** [comment]
Hi there, I think you might be mixing things a bit: this is an implementation of the lzw compression written in rust.
Nothing more, nothing less, so I would not increase its complexity.
And you are looking for some compression tools written in Java.

So I'm not really sure what you are asking here but I don't think I can help you, these are two completely different projects.

**Comment by v1gnesh** [comment]
> And you are looking for some compression tools written in Java.

It has both compr and decompr. And the algo is based on LZW, so was wondering if you had time/interest to add support for a variant/flavour (like it currently supports tiff gif).

**Comment by redwarp** [comment]
Well, sorry, but I really know nothing about this IBM thing, so I won't really be able to provide any help or support for it 🥲

**Comment by v1gnesh** [comment]
No worries, thanks for responding (and again for sharing your work here).
